title: Samson Zhang
email: samsonzhang@wwsalmon.com
description: The portfolio and personal website of Samson Zhang, filmmaker, photographer, designer, and developer, among other things. Currently a student at Phillips Academy, class of 2020.
baseurl: ""
url: "https://www.wwsalmon.com"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

twitter:
  username: wwsalmon
  card: summary

sass:
  sass_dir: _sass
  style: compressed

logo: favicon.png

collections:
  portfolio:
    output: true
  video:
    output: true