title: Samson Zhang
email: samsonzhang@wwsalmon.com
description: The portfolio and personal website of Samson Zhang, filmmaker, photographer, designer, and developer, among other things. Currently a student at Phillips Academy, class of 2020.
baseurl: ""
url: "https://www.samsonzhang.com/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  # - jekyll-manager
  - jekyll/tagging

twitter:
  username: wwsalmon
  card: summary

sass:
  sass_dir: _sass
  style: compressed

logo: favicon.png

collections:
  portfolio:
    output: true
  film:
    output: true
  projects:
    output: true
  design:
    output: true

include:
- _redirects

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

tag_page_layout: tagpage
tag_page_dir: blog